#!/usr/bin/env node
/**
 * Violet Glass build script — zero dependencies.
 *
 * For each variant, takes the template JSON from src/, injects
 * `custom_css` (banner + vars-<variant>.css + base.css) and writes the
 * importable theme file to dist/.
 *
 * Usage:
 *   node build.mjs                       build dist/
 *   node build.mjs --install [path]      build, then copy into a SillyTavern
 *                                        themes folder (default: sibling
 *                                        ../SillyTavern/data/default-user/themes)
 *   node build.mjs --watch [--install]   rebuild on every change under src/
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, watch } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const SRC = join(root, 'src');
const DIST = join(root, 'dist');
const DEFAULT_THEMES_DIR = resolve(root, '..', 'SillyTavern', 'data', 'default-user', 'themes');

const VARIANTS = [
    { template: 'theme-dark.json', vars: 'vars-dark.css' },
    { template: 'theme-light.json', vars: 'vars-light.css' },
];

function build() {
    mkdirSync(DIST, { recursive: true });
    const base = readFileSync(join(SRC, 'base.css'), 'utf8');
    const outputs = [];

    for (const { template, vars } of VARIANTS) {
        const theme = JSON.parse(readFileSync(join(SRC, template), 'utf8'));
        const tokens = readFileSync(join(SRC, vars), 'utf8');
        const banner = `/* ${theme.name} — generated by build.mjs. Edit src/ in the theme repo, not this file. */`;
        theme.custom_css = `${banner}\n\n${tokens.trim()}\n\n${base.trim()}\n`;

        // SillyTavern refuses themes whose custom_css contains @import (power-user.js).
        if (theme.custom_css.includes('@import')) {
            throw new Error(`${theme.name}: custom_css must not contain @import`);
        }

        const outPath = join(DIST, `${theme.name}.json`);
        writeFileSync(outPath, JSON.stringify(theme, null, 4) + '\n');
        outputs.push(outPath);
        console.log(`built     ${outPath}`);
    }

    return outputs;
}

function install(outputs, target) {
    if (!existsSync(target)) {
        throw new Error(
            `install target does not exist: ${target}\n` +
            'Pass the path to your SillyTavern themes folder, e.g.\n' +
            '  node build.mjs --install /path/to/SillyTavern/data/<user>/themes',
        );
    }
    for (const file of outputs) {
        const dest = join(target, basename(file));
        copyFileSync(file, dest);
        console.log(`installed ${dest}`);
    }
}

const args = process.argv.slice(2);
const watchMode = args.includes('--watch');
const installIdx = args.indexOf('--install');
const installTarget = installIdx === -1
    ? null
    : (args[installIdx + 1] && !args[installIdx + 1].startsWith('--'))
        ? resolve(args[installIdx + 1])
        : DEFAULT_THEMES_DIR;

function run() {
    try {
        const outputs = build();
        if (installTarget) {
            install(outputs, installTarget);
        }
    } catch (err) {
        console.error(err.message);
        process.exitCode = 1;
    }
}

run();

if (watchMode) {
    let timer = null;
    watch(SRC, () => {
        clearTimeout(timer);
        timer = setTimeout(() => {
            console.log('--- rebuild ---');
            run();
        }, 100);
    });
    console.log(`watching ${SRC} ...`);
}
